### ISSUE TITLE
I need help,it don not work in img2img

### ISSUE THREAD

**Issue by tianxiadiyishuaiuio** [Haoming02/sd-forge-ic-light#7]
![image](https://github.com/user-attachments/assets/8256f139-9ca6-4f51-b8e1-2d777dbc2b99)
*** Error running before_process: E:\SD_WEBUI-aki_v4.4\extensions\sd-forge-ic-light\scripts\ic_light_script.py
    Traceback (most recent call last):
      File "E:\SD_WEBUI-aki_v4.4\modules\scripts.py", line 824, in before_process
        script.before_process(p, *script_args)
      File "E:\SD_WEBUI-aki_v4.4\extensions\sd-forge-ic-light\scripts\ic_light_script.py", line 257, in before_process
        args = ICLightArgs.fetch_from(p)
      File "E:\SD_WEBUI-aki_v4.4\extensions\sd-forge-ic-light\libiclight\args.py", line 210, in fetch_from
        return ICLightArgs(**args[0])
      File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
        values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
      File "pydantic\main.py", line 1102, in pydantic.main.validate_model
        values = validator(cls_, values)
      File "E:\SD_WEBUI-aki_v4.4\extensions\sd-forge-ic-light\libiclight\args.py", line 182, in process_input_fg
        input_fg_rgb: np.ndarray = run_rmbg(input_fg)
      File "E:\SD_WEBUI-aki_v4.4\extensions\sd-forge-ic-light\libiclight\rembg_utils.py", line 41, in run_rmbg
        session=rembg.new_session(model),
      File "E:\SD_WEBUI-aki_v4.4\python\lib\site-packages\rembg\session_factory.py", line 26, in new_session
        return session_class(model_name, sess_opts, providers, *args, **kwargs)
      File "E:\SD_WEBUI-aki_v4.4\python\lib\site-packages\rembg\sessions\base.py", line 31, in __init__
        self.inner_session = ort.InferenceSession(
      File "E:\SD_WEBUI-aki_v4.4\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 360, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "E:\SD_WEBUI-aki_v4.4\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 408, in _create_inference_session
        sess.initialize_session(providers, provider_options, disabled_optimizers)
    RuntimeError: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1106 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "E:\SD_WEBUI-aki_v4.4\python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

**Comment by Haoming02** [comment]
你用的應該原本的 repo 吧? 我的 fork 已經修過這個囉~

You seem to have opened the issue on a wrong repo, as this issue has already been fixed in my fork.
